name: "Jest Code Coverage Report"
description: "Comments a pull request with the jest code coverage"
author: "Zeeshan Ahmad"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "Github token"
    required: true
  test-command:
    description: "Specify a command to run the tests"
    required: false
  max-buffer:
    description: "Max buffer to run the tests"
    required: false
runs:
  using: "node12"
  main: "index.js"
